Repository strapi/documentation, pull requests merged in 2021-08, with the labels that each got.

#376 Fix broken feature request link in DO notice
  docs/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/digitalocean-app-platform.md
Labels: source: developer-docs, type: bug

#378 Switch "Hands-on" and "Starters" tabs in QSG
  docs/developer-docs/latest/getting-started/quick-start.md
Labels: source: developer-docs, type: internal

#369 fix typo isAuthenticated for plugin
  docs/developer-docs/latest/development/backend-customization.md
Labels: source: developer-docs

#380 Remove normal Google Analytics and add GTM
  docs/.vuepress/config.js
  docs/package.json
Labels: type: internal

#381 Update node env var to fix build bug
  docs/.vuepress/config.js
  docs/yarn.lock
Labels: source: repo

#382 Add a local node script for legacy
  docs/package.json
Labels: source: repo

#383 Update logger instance (Winston instead of Pino)
  docs/developer-docs/latest/developer-resources/global-strapi/api-reference.md
  docs/developer-docs/latest/getting-started/introduction.md
Labels: type: internal, target:v4

#384 Removed Slack from the Navbar Community dropdown
  docs/.vuepress/config.js
Labels: type: internal, target:v3

#387 Add hiring link
  docs/.vuepress/config.js
Labels: source: repo, target:v3

#370 Case for 1 can be handled in loop - fix in docs
  docs/developer-docs/latest/development/plugins/upload.md
Labels: source: developer-docs, target:v3

#372 Change code snippet for service create customisation
  docs/developer-docs/latest/development/backend-customization.md
Labels: source: developer-docs, target:v3

#393 Highlight active tab in blue (instead of default VuePress green)
  docs/.vuepress/styles/strapi-custom-blocks.styl
Labels: source: repo, type: internal, target:v3
