Repository strapi/documentation, pull requests merged in 2024-05, with the labels that each got.

#2097 pr: chore - Improving routes page
  docusaurus/docs/dev-docs/backend-customization/routes.md
Labels: source: Dev Docs, pr: fix

#2098 Estimation of time to complete all the steps at the beginning of the Quick Start Guide
  docusaurus/docs/dev-docs/quick-start.md
Labels: severity: low, internal

#2107 Security information update to users-permissions
  docusaurus/docs/dev-docs/plugins/users-permissions.md
  docusaurus/static/img/assets/users-permissions/sso-config-custom-validator.png
  docusaurus/static/img/assets/users-permissions/sso-config-custom-validator_DARK.png
Labels: source: Dev Docs, internal, pr: new content, target: v4, size: small, temp: port to v5

#2112 docs: add codemods command
  docusaurus/docs/dev-docs/upgrade-tool.md
Labels: v5

#2111 Rewording of TOC/sidebar introduction labels
  docusaurus/sidebars.js
Labels: source: Dev Docs, pr: fix, internal

#2105 Fix typo in admin-panel-customization.md
  docusaurus/docs/dev-docs/admin-panel-customization.md
Labels: source: Dev Docs, pr: fix

#2104 fix: import should be same directory ../ -> ./
  docusaurus/docs/dev-docs/admin-panel-customization.md
Labels: source: Dev Docs, pr: fix

#2108 Fix parameter name in database configuration for MySQL2
  docusaurus/docs/dev-docs/configurations/database.md
Labels: source: Dev Docs, pr: fix, temp: port to v5

#2102 Fixed file structure alignment
  docusaurus/src/components/ProjectStructure.js
Labels: source: Dev Docs, pr: fix, temp: port to v5

#2099 Created component for numbered lists referring to annotated screenshots
  docusaurus/docs/dev-docs/api/rest/guides/understanding-populate.md
  docusaurus/docs/user-docs/content-manager/introduction-to-content-manager.md
  docusaurus/docs/user-docs/content-type-builder/managing-content-types.md
  docusaurus/docs/user-docs/media-library/introduction-to-the-media-library.md
  docusaurus/docs/user-docs/media-library/managing-assets.md
  docusaurus/docs/user-docs/media-library/organizing-assets-with-folders.md
  docusaurus/docs/user-docs/releases/managing-a-release.md
  docusaurus/docs/user-docs/users-roles-permissions/managing-administrators.md
  docusaurus/src/components/ScreenshotNumberReference.jsx
  docusaurus/src/theme/MDXComponents.js
Labels: source: repo, internal

#2109 Plugin CLI update for @strapi/sdk-plugin package
  docusaurus/docs/dev-docs/plugins/development/plugin-cli.md
  docusaurus/docs/dev-docs/plugins/guides/use-the-plugin-cli.md
Labels: v5

#2114 Addition of "deploy on push" option in Update Repository documentation
  docusaurus/docs/cloud/projects/settings.md
Labels: pr: updated content, internal, source: Strapi Cloud

#2116 Add FAQ section for 'Cannot find module @strapi/XXX' build error
  docusaurus/docs/dev-docs/faq.md
Labels: pr: updated content, v5
