Repository strapi/documentation, pull requests merged in 2024-04, with the labels that each got.

#2069 Adding bash command to list strapi controllers
  docusaurus/docs/dev-docs/cli.md
Labels: source: Dev Docs, pr: fix, temp: port to v5

#2083 [Strapi 5] Document better-sqlite3 breaking change
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes.md
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes/only-better-sqlite3-for-sqlite.md
  docusaurus/sidebars.js
Labels: internal, v5

#2081 Fixes incorrect code example in providers.md
  docusaurus/docs/dev-docs/providers.md
Labels: source: Dev Docs, pr: fix

#2084 Add missing available options for the client database configuration
  docusaurus/docs/dev-docs/configurations/database.md
Labels: source: Dev Docs, pr: fix

#2085 Document using strapi instance for migrations
  docusaurus/docs/dev-docs/database-migrations.md
Labels: source: Dev Docs

#2092 fix: remove verbose option
  docusaurus/docs/dev-docs/cli.md
Labels: internal, v5

#2087 [Strapi 5] Updated homepage
  docusaurus/docusaurus.config.js
  docusaurus/src/components/Container/container.module.scss
  docusaurus/src/components/FeaturesList/features-list.module.scss
  docusaurus/src/pages/home/Home.jsx
  docusaurus/src/pages/home/_home.content.js
  docusaurus/src/scss/_tokens.scss
  docusaurus/static/img/assets/home/preview--cloud-docs.png
  docusaurus/static/img/assets/icons/cloud.svg
Labels: internal, v5

#2093 [Strapi 5] Entity Service → Document Service: Breaking change + migration reference
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes.md
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes/entity-service-deprecated.md
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes/publication-state-removed.md
  docusaurus/docs/dev-docs/migration/v4-to-v5/guides/from-entity-service-to-document-service.md
  docusaurus/sidebars.js
Labels: internal, v5

#2094 Add missing comma in example code for middlewares configuration
  docusaurus/docs/dev-docs/configurations/middlewares.md
Labels: pr: fix

#2082 [Strapi 5] Document breaking change for Admin RBAC updates
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes.md
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes/admin-panel-rbac-store-updated.md
  docusaurus/sidebars.js
Labels: internal, v5

#2096 [Strapi 5] Breaking change for default input validation
  docusaurus/docs/dev-docs/backend-customization/controllers.md
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes.md
  docusaurus/docs/dev-docs/migration/v4-to-v5/breaking-changes/default-input-validation.md
  docusaurus/sidebars.js
Labels: internal, v5
